#!/bin/sh
RUNPATH=/data/kplusaddon/FFC/config/
RUNPATHFFC=/data/kplusaddon/FFC/Release/etc

if [ "`whoami`" != "$USERID" ] ; then
   echo "Only the user 'kplus' can run this script ..."
   exit 1
fi

for file in WSPaymentService
do
	cd ${RUNPATHFFC}
	./mch.sh stop ${RUNPATH}$file 
done
